### ISSUE TITLE
Error when running cam.play_camera()

### ISSUE THREAD

**Issue by s-tarz** [matham/thorcam#11]
Hello, I am using the 1500M-GE scientific camera with anaconda on windows 10.
I can connect to the camera just fine and change the exposure settings and such, but whenever I try to run cam.play_camera() I get this error:

cam.play_camera()
Received "playing" with value "True"
ERROR:root:'IImageData' object has no attribute 'ImageData_monoOrBGR'
ERROR:root:Traceback (most recent call last):
  File "C:\Users\STarazi\Anaconda3\envs\thor\lib\site-packages\thorcam\camera_dot_net.py", line 477, in camera_run
    data = self.read_frame(cam)
  File "C:\Users\STarazi\Anaconda3\envs\thor\lib\site-packages\thorcam\camera_dot_net.py", line 398, in read_frame
    data = [as_numpy_array(frame.ImageData.ImageData_monoOrBGR)]
AttributeError: 'IImageData' object has no attribute 'ImageData_monoOrBGR'

Received "exception" with value "["'IImageData' object has no attribute 'ImageData_monoOrBGR'", 'Traceback (most recent call last):\n  File "C:\\Users\\STarazi\\Anaconda3\\envs\\thor\\lib\\site-packages\\thorcam\\camera_dot_net.py", line 477, in camera_run\n    data = self.read_frame(cam)\n  File "C:\\Users\\STarazi\\Anaconda3\\envs\\thor\\lib\\site-packages\\thorcam\\camera_dot_net.py", line 398, in read_frame\n    data = [as_numpy_array(frame.ImageData.ImageData_monoOrBGR)]\nAttributeError: \'IImageData\' object has no attribute \'ImageData_monoOrBGR\'\n']"
Received "cam_closed" with value "None"

Any help would be much appreciated! Thanks.

**Comment by matham** [comment]
I got a similar report from someone by email and I was unable to trace down the issue, partially because I don't have access to such a camera. 

Specifically, looking at the C# Thor API, `IImageData` inherits from a `IImageDataUShort1D` that has the `ImageData_monoOrBGR` attribute. When writing C# it says that you need to first cast `IImageData` to `IImageDataUShort1D` before accessing `ImageData_monoOrBGR`. But from their own matlab examples you don't need to do it and it works similarly without casting in Python for my camera (see other usage: https://github.com/search?p=1&q=ImageData_monoOrBGR&type=Code).

So, somehow, for your camera, the object you're getting does need to be casted. Unfortunately, I was unable to work out how to cast it using `pythonnet`. The official way of casting (passing the object to the superclass) fails.

If you're willing to experiment, can you try editing `C:\Users\STarazi\Anaconda3\envs\thor\lib\site-packages\thorcam\camera_dot_net.py`. Specifically at the corresponding lines here: https://github.com/matham/thorcam/blob/master/thorcam/camera_dot_net.py#L376, can you add `print(frame.ImageData, type(frame.ImageData), list(dir(frame.ImageData)))` and comment the results?

**Comment by s-tarz** [comment]
This is the output when adding that print line:

cam.play_camera()
Received "playing" with value "True"

IImageDataUShort1D: Width_pixels=1392, Height_pixels=1040, BitDepth=12, NumberOfChannels=1, ImageData_monoOrBGR=1447680 (length) <class 'Thorlabs.TSI.ImageDataInterfaces.IImageData'> ['BitDepth', 'Equals', 'GetHashCode', 'GetType', 'Height_pixels', 'ImageDataFormat', 'NumberOfChannels', 'ToBitmapSource_FormatBgr24', 'ToBitmapSource_FormatRgb48OrGray16', 'ToBitmap_Format24bppRgb', 'ToString', 'Width_pixels', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'get_BitDepth', 'get_Height_pixels', 'get_ImageDataFormat', 'get_NumberOfChannels', 'get_Width_pixels']

**Comment by matham** [comment]
Thanks! I think I found a pythonnet workaround to get the actual property. Can you copy the contents of this file into the file you previously edited and check if that fixes it? https://github.com/matham/thorcam/blob/9ab5996292a9c4afb296d072523f4bca46cfb83d/thorcam/camera_dot_net.py.

**Comment by s-tarz** [comment]
It worked! Thank you!

**Comment by matham** [comment]
Great! I just made a new release with the fix.
