### ISSUE TITLE
Compatibilty to new python versions/anaconda

### ISSUE THREAD

**Issue by TimVog** [matham/thorcam#7]
Hi, first of all thanks for the program.
I'm using Thorlabs DCC1545M-GL on Windows 10. The newest Thorlabs Software was installed and I can also get a picture. The uc480 can also detect a properly working camera.
![grafik](https://user-images.githubusercontent.com/32876663/105039594-08267e00-5a61-11eb-9229-03704924665f.png)

1. I tried to run it first with anaconda `Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] on win32`
where I just installed `pip install thorcam` (because, so far, anaconda and pip always came along).  Strangely, after following your example, I don't get any feedback in the console, i.e. `cam = MyThorCam()` gets executed and I see in the variable viewer that I have the object, but there is no print response. In the end the program doesn't see any cameras.
```
>>> cam = MyThorCam()
>>> cam.start_cam_process()
>>> cam.refresh_cameras()
Received "serials" with value "[]"
```
2. Instead of using anaconda, I used pure Python and created a virtualenv like you mentioned in Issue #6 but this failed since pythonnet is not compatible (currently) with Python3.9

3. Instead of using Python 3.9, I downloaded 3.8, where the pip installation runs flawlessly. Unfortunately, also here the detection of the camera is not possible, but I get a different error:
```
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from thorcam.camera import ThorCam
>>> class MyThorCam(ThorCam):
...     def received_camera_response(self, msg, value):
...         super(MyThorCam, self).received_camera_response(msg, value)
...         if msg == 'image':
...             return
...         print('Received "{}" with value "{}"'.format(msg, value))
...     def got_image(self, image, count, queued_count, t):
...         print('Received image "{}" with time "{}" and counts "{}", "{}"'
...               .format(image, t, count, queued_count))
...
>>> cam = MyThorCam()
>>> cam.start_cam_process()
>>> cam.refresh_cameras()
>>> EDT pdv open failed.
Check board installation and unit number, and try restarting the computer
Received "serials" with value "[]"
```

Any tips how this can be resolved?

**Comment by matham** [comment]
Looking through their [docs](https://www.thorlabs.com/software_pages/ViewSoftwarePage.cfm?Code=ThorCam) you can see they offer two SDKs one for "Scientific Cameras" and one for "DCx Series Cameras". And they are not compatible with each other as their underlying systems are different. I vaguely remember talking to their support about this and I think they were saying that long term they are trying to stick with the "Scientific Cameras" SDK, but don't quote me on that.

The camera I tested was a scientific camera and that's what I used when building this library to test with. So this library is not compatible with your camera I believe, unfortunately. But it shouldn't be too hard to implement something to run your camera.

To give you an idea of what you need to do, you can see what I did for thorcam. [This](https://github.com/matham/thorcam/blob/master/thorcam/camera_dot_net.py#L627) sets up the `.Net` dll interfaces. [This](https://github.com/matham/thorcam/blob/master/thorcam/camera_dot_net.py#L652) lists the cameras and since it doesn't list yours it basically means it's not compatible. [This](https://github.com/matham/thorcam/blob/master/thorcam/camera_dot_net.py#L84) class basically runs the camera. It's all run from a second process through an internal socket because pythonnet can play havoc with other python libraries, in my experience.

Anyway, the process is to download and extract the "Windows SDK and Doc. for DCx Series Cameras" from [here](https://www.thorlabs.com/software_pages/ViewSoftwarePage.cfm?Code=ThorCam#tabs-147). Look in the the "DCx_Camera_Documentation" directory for the `DCx_MATLAB_ProgInterface.pdf` for a simple example from matlab (see translated code below) and `DCx_DotNET_ProgInterface.pdf` for the full API.

I translated the following code from the matlab example to Python. However, I don't have a camera to test with so you'll probably have to tinker a little to get the API right:


```py
# this requires pythonnet
import clr
import os

bin_path = r'C:\Users\user\Downloads\DCx_Camera_SDK\Develop\DotNet'
driver_path = r'C:\Users\user\Downloads\DCx_Camera_Drivers\64'

os.environ['PATH'] += os.pathsep + bin_path + os.pathsep + driver_path
clr.AddReference(os.path.join(bin_path, 'uc480DotNet.dll'))
from uc480 import Camera, Defines

# get list of all possible status, comment out as needed
# print(dir(Defines.Status))

# create camera
cam = Camera()
# print all camera methods
# print(dir(cam))

# init first camera
status = cam.Init(0)
if status != Defines.Status.SUCCESS:
    ValueError(f'Got error code {status}')

# Set display mode to bitmap (DiB)
cam.Display.Mode.Set(Defines.DisplayMode.DiB)

# Set color mode to 8-bit RGB
cam.PixelFormat.Set(Defines.ColorMode.RGBA8Packed)

# Set trigger mode to software (single image acquisition)
cam.Trigger.Set(Defines.TriggerMode.Software)

# Allocate image memory
mem_id = cam.Memory.Allocate(True)

# Obtain image information
w, h, pixel_depth, pitch = cam.Memory.Inquire(mem_id)
# Acquire image
cam.Acquisition.Freeze(Defines.DeviceParameter.Wait)
# Copy image from memory
buffer = cam.Memory.CopyToArray(mem_id)

# Close camera
cam.Exit()
```

**Comment by matham** [comment]
I think I'm going to make it clear in the readme that it doesn't support DCx cameras.
